// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/v1/echomap.proto

package echomapv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EchoMap_FetchChallenge_FullMethodName    = "/echomap.v1.EchoMap/FetchChallenge"
	EchoMap_SubmitMeasurement_FullMethodName = "/echomap.v1.EchoMap/SubmitMeasurement"
)

// EchoMapClient is the client API for EchoMap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoMapClient interface {
	// Get a challenge with probe targets to ping
	FetchChallenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error)
	// Submit measured latencies for geolocation calculation
	SubmitMeasurement(ctx context.Context, in *MeasurementRequest, opts ...grpc.CallOption) (*MeasurementResponse, error)
}

type echoMapClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoMapClient(cc grpc.ClientConnInterface) EchoMapClient {
	return &echoMapClient{cc}
}

func (c *echoMapClient) FetchChallenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChallengeResponse)
	err := c.cc.Invoke(ctx, EchoMap_FetchChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoMapClient) SubmitMeasurement(ctx context.Context, in *MeasurementRequest, opts ...grpc.CallOption) (*MeasurementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeasurementResponse)
	err := c.cc.Invoke(ctx, EchoMap_SubmitMeasurement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoMapServer is the server API for EchoMap service.
// All implementations must embed UnimplementedEchoMapServer
// for forward compatibility.
type EchoMapServer interface {
	// Get a challenge with probe targets to ping
	FetchChallenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error)
	// Submit measured latencies for geolocation calculation
	SubmitMeasurement(context.Context, *MeasurementRequest) (*MeasurementResponse, error)
	mustEmbedUnimplementedEchoMapServer()
}

// UnimplementedEchoMapServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEchoMapServer struct{}

func (UnimplementedEchoMapServer) FetchChallenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchChallenge not implemented")
}
func (UnimplementedEchoMapServer) SubmitMeasurement(context.Context, *MeasurementRequest) (*MeasurementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitMeasurement not implemented")
}
func (UnimplementedEchoMapServer) mustEmbedUnimplementedEchoMapServer() {}
func (UnimplementedEchoMapServer) testEmbeddedByValue()                 {}

// UnsafeEchoMapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoMapServer will
// result in compilation errors.
type UnsafeEchoMapServer interface {
	mustEmbedUnimplementedEchoMapServer()
}

func RegisterEchoMapServer(s grpc.ServiceRegistrar, srv EchoMapServer) {
	// If the following call panics, it indicates UnimplementedEchoMapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EchoMap_ServiceDesc, srv)
}

func _EchoMap_FetchChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoMapServer).FetchChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EchoMap_FetchChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoMapServer).FetchChallenge(ctx, req.(*ChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EchoMap_SubmitMeasurement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeasurementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoMapServer).SubmitMeasurement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EchoMap_SubmitMeasurement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoMapServer).SubmitMeasurement(ctx, req.(*MeasurementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EchoMap_ServiceDesc is the grpc.ServiceDesc for EchoMap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EchoMap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echomap.v1.EchoMap",
	HandlerType: (*EchoMapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchChallenge",
			Handler:    _EchoMap_FetchChallenge_Handler,
		},
		{
			MethodName: "SubmitMeasurement",
			Handler:    _EchoMap_SubmitMeasurement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/echomap.proto",
}
