// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/v1/echomap.proto

package echomapv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_CONFIRMED   Status = 1
	Status_STATUS_PLAUSIBLE   Status = 2
	Status_STATUS_SUSPICIOUS  Status = 3
	Status_STATUS_REJECTED    Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_CONFIRMED",
		2: "STATUS_PLAUSIBLE",
		3: "STATUS_SUSPICIOUS",
		4: "STATUS_REJECTED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_CONFIRMED":   1,
		"STATUS_PLAUSIBLE":   2,
		"STATUS_SUSPICIOUS":  3,
		"STATUS_REJECTED":    4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_echomap_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_v1_echomap_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_echomap_proto_rawDescGZIP(), []int{0}
}

type ChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeRequest) Reset() {
	*x = ChallengeRequest{}
	mi := &file_proto_v1_echomap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeRequest) ProtoMessage() {}

func (x *ChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_echomap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeRequest.ProtoReflect.Descriptor instead.
func (*ChallengeRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_echomap_proto_rawDescGZIP(), []int{0}
}

func (x *ChallengeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Targets       []*ProbeTarget         `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChallengeResponse) Reset() {
	*x = ChallengeResponse{}
	mi := &file_proto_v1_echomap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeResponse) ProtoMessage() {}

func (x *ChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_echomap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChallengeResponse.ProtoReflect.Descriptor instead.
func (*ChallengeResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_echomap_proto_rawDescGZIP(), []int{1}
}

func (x *ChallengeResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ChallengeResponse) GetTargets() []*ProbeTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *ChallengeResponse) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ChallengeResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ChallengeResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ProbeTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	PingCount     int32                  `protobuf:"varint,4,opt,name=ping_count,json=pingCount,proto3" json:"ping_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeTarget) Reset() {
	*x = ProbeTarget{}
	mi := &file_proto_v1_echomap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeTarget) ProtoMessage() {}

func (x *ProbeTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_echomap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeTarget.ProtoReflect.Descriptor instead.
func (*ProbeTarget) Descriptor() ([]byte, []int) {
	return file_proto_v1_echomap_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeTarget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProbeTarget) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProbeTarget) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProbeTarget) GetPingCount() int32 {
	if x != nil {
		return x.PingCount
	}
	return 0
}

type MeasurementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Measurements  []*ProbeMeasurement    `protobuf:"bytes,3,rep,name=measurements,proto3" json:"measurements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasurementRequest) Reset() {
	*x = MeasurementRequest{}
	mi := &file_proto_v1_echomap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementRequest) ProtoMessage() {}

func (x *MeasurementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_echomap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementRequest.ProtoReflect.Descriptor instead.
func (*MeasurementRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_echomap_proto_rawDescGZIP(), []int{3}
}

func (x *MeasurementRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *MeasurementRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MeasurementRequest) GetMeasurements() []*ProbeMeasurement {
	if x != nil {
		return x.Measurements
	}
	return nil
}

type ProbeMeasurement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProbeId       string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	RttsUs        []int32                `protobuf:"varint,2,rep,packed,name=rtts_us,json=rttsUs,proto3" json:"rtts_us,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeMeasurement) Reset() {
	*x = ProbeMeasurement{}
	mi := &file_proto_v1_echomap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeMeasurement) ProtoMessage() {}

func (x *ProbeMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_echomap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeMeasurement.ProtoReflect.Descriptor instead.
func (*ProbeMeasurement) Descriptor() ([]byte, []int) {
	return file_proto_v1_echomap_proto_rawDescGZIP(), []int{4}
}

func (x *ProbeMeasurement) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeMeasurement) GetRttsUs() []int32 {
	if x != nil {
		return x.RttsUs
	}
	return nil
}

type MeasurementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       *Verdict               `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"`
	Region        *Region                `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Exclusions    []*Exclusion           `protobuf:"bytes,3,rep,name=exclusions,proto3" json:"exclusions,omitempty"`
	ProbeResults  []*ProbeResult         `protobuf:"bytes,4,rep,name=probe_results,json=probeResults,proto3" json:"probe_results,omitempty"`
	Spoofing      *SpoofingIndicators    `protobuf:"bytes,5,opt,name=spoofing,proto3" json:"spoofing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeasurementResponse) Reset() {
	*x = MeasurementResponse{}
	mi := &file_proto_v1_echomap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeasurementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeasurementResponse) ProtoMessage() {}

func (x *MeasurementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_echomap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeasurementResponse.ProtoReflect.Descriptor instead.
func (*MeasurementResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_echomap_proto_rawDescGZIP(), []int{5}
}

func (x *MeasurementResponse) GetVerdict() *Verdict {
	if x != nil {
		return x.Verdict
	}
	return nil
}

func (x *MeasurementResponse) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *MeasurementResponse) GetExclusions() []*Exclusion {
	if x != nil {
		return x.Exclusions
	}
	return nil
}

func (x *MeasurementResponse) GetProbeResults() []*ProbeResult {
	if x != nil {
		return x.ProbeResults
	}
	return nil
}

func (x *MeasurementResponse) GetSpoofing() *SpoofingIndicators {
	if x != nil {
		return x.Spoofing
	}
	return nil
}

type Verdict struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=echomap.v1.Status" json:"status,omitempty"`
	Confidence        float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	PhysicsConfidence float64                `protobuf:"fixed64,3,opt,name=physics_confidence,json=physicsConfidence,proto3" json:"physics_confidence,omitempty"` // Layer 1 only (speed of light)
	NearestProbe      string                 `protobuf:"bytes,4,opt,name=nearest_probe,json=nearestProbe,proto3" json:"nearest_probe,omitempty"`                  // Probe ID with lowest RTT
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Verdict) Reset() {
	*x = Verdict{}
	mi := &file_proto_v1_echomap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verdict) ProtoMessage() {}

func (x *Verdict) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_echomap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verdict.ProtoReflect.Descriptor instead.
func (*Verdict) Descriptor() ([]byte, []int) {
	return file_proto_v1_echomap_proto_rawDescGZIP(), []int{6}
}

func (x *Verdict) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Verdict) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Verdict) GetPhysicsConfidence() float64 {
	if x != nil {
		return x.PhysicsConfidence
	}
	return 0
}

func (x *Verdict) GetNearestProbe() string {
	if x != nil {
		return x.NearestProbe
	}
	return ""
}

type Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_proto_v1_echomap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_echomap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_proto_v1_echomap_proto_rawDescGZIP(), []int{7}
}

func (x *Region) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Region) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Region) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *Region) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Exclusion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exclusion) Reset() {
	*x = Exclusion{}
	mi := &file_proto_v1_echomap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exclusion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exclusion) ProtoMessage() {}

func (x *Exclusion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_echomap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exclusion.ProtoReflect.Descriptor instead.
func (*Exclusion) Descriptor() ([]byte, []int) {
	return file_proto_v1_echomap_proto_rawDescGZIP(), []int{8}
}

func (x *Exclusion) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Exclusion) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type ProbeResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProbeId           string                 `protobuf:"bytes,1,opt,name=probe_id,json=probeId,proto3" json:"probe_id,omitempty"`
	RttMs             float64                `protobuf:"fixed64,2,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`
	JitterMs          float64                `protobuf:"fixed64,3,opt,name=jitter_ms,json=jitterMs,proto3" json:"jitter_ms,omitempty"`
	MaxDistanceKm     float64                `protobuf:"fixed64,4,opt,name=max_distance_km,json=maxDistanceKm,proto3" json:"max_distance_km,omitempty"`
	DatasetExpectedMs float64                `protobuf:"fixed64,5,opt,name=dataset_expected_ms,json=datasetExpectedMs,proto3" json:"dataset_expected_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_proto_v1_echomap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_echomap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_proto_v1_echomap_proto_rawDescGZIP(), []int{9}
}

func (x *ProbeResult) GetProbeId() string {
	if x != nil {
		return x.ProbeId
	}
	return ""
}

func (x *ProbeResult) GetRttMs() float64 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *ProbeResult) GetJitterMs() float64 {
	if x != nil {
		return x.JitterMs
	}
	return 0
}

func (x *ProbeResult) GetMaxDistanceKm() float64 {
	if x != nil {
		return x.MaxDistanceKm
	}
	return 0
}

func (x *ProbeResult) GetDatasetExpectedMs() float64 {
	if x != nil {
		return x.DatasetExpectedMs
	}
	return 0
}

type SpoofingIndicators struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	VpnLikely            bool                   `protobuf:"varint,1,opt,name=vpn_likely,json=vpnLikely,proto3" json:"vpn_likely,omitempty"`
	JitterAbnormal       bool                   `protobuf:"varint,2,opt,name=jitter_abnormal,json=jitterAbnormal,proto3" json:"jitter_abnormal,omitempty"`
	RatioInconsistent    bool                   `protobuf:"varint,3,opt,name=ratio_inconsistent,json=ratioInconsistent,proto3" json:"ratio_inconsistent,omitempty"`
	PhysicallyImpossible bool                   `protobuf:"varint,4,opt,name=physically_impossible,json=physicallyImpossible,proto3" json:"physically_impossible,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SpoofingIndicators) Reset() {
	*x = SpoofingIndicators{}
	mi := &file_proto_v1_echomap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpoofingIndicators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpoofingIndicators) ProtoMessage() {}

func (x *SpoofingIndicators) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_echomap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpoofingIndicators.ProtoReflect.Descriptor instead.
func (*SpoofingIndicators) Descriptor() ([]byte, []int) {
	return file_proto_v1_echomap_proto_rawDescGZIP(), []int{10}
}

func (x *SpoofingIndicators) GetVpnLikely() bool {
	if x != nil {
		return x.VpnLikely
	}
	return false
}

func (x *SpoofingIndicators) GetJitterAbnormal() bool {
	if x != nil {
		return x.JitterAbnormal
	}
	return false
}

func (x *SpoofingIndicators) GetRatioInconsistent() bool {
	if x != nil {
		return x.RatioInconsistent
	}
	return false
}

func (x *SpoofingIndicators) GetPhysicallyImpossible() bool {
	if x != nil {
		return x.PhysicallyImpossible
	}
	return false
}

var File_proto_v1_echomap_proto protoreflect.FileDescriptor

const file_proto_v1_echomap_proto_rawDesc = "" +
	"\n" +
	"\x16proto/v1/echomap.proto\x12\n" +
	"echomap.v1\"/\n" +
	"\x10ChallengeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xbd\x01\n" +
	"\x11ChallengeResponse\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x121\n" +
	"\atargets\x18\x02 \x03(\v2\x17.echomap.v1.ProbeTargetR\atargets\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\"d\n" +
	"\vProbeTarget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"ping_count\x18\x04 \x01(\x05R\tpingCount\"\x8f\x01\n" +
	"\x12MeasurementRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12@\n" +
	"\fmeasurements\x18\x03 \x03(\v2\x1c.echomap.v1.ProbeMeasurementR\fmeasurements\"F\n" +
	"\x10ProbeMeasurement\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12\x17\n" +
	"\artts_us\x18\x02 \x03(\x05R\x06rttsUs\"\xa1\x02\n" +
	"\x13MeasurementResponse\x12-\n" +
	"\averdict\x18\x01 \x01(\v2\x13.echomap.v1.VerdictR\averdict\x12*\n" +
	"\x06region\x18\x02 \x01(\v2\x12.echomap.v1.RegionR\x06region\x125\n" +
	"\n" +
	"exclusions\x18\x03 \x03(\v2\x15.echomap.v1.ExclusionR\n" +
	"exclusions\x12<\n" +
	"\rprobe_results\x18\x04 \x03(\v2\x17.echomap.v1.ProbeResultR\fprobeResults\x12:\n" +
	"\bspoofing\x18\x05 \x01(\v2\x1e.echomap.v1.SpoofingIndicatorsR\bspoofing\"\xa9\x01\n" +
	"\aVerdict\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.echomap.v1.StatusR\x06status\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12-\n" +
	"\x12physics_confidence\x18\x03 \x01(\x01R\x11physicsConfidence\x12#\n" +
	"\rnearest_probe\x18\x04 \x01(\tR\fnearestProbe\"_\n" +
	"\x06Region\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKm\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\"C\n" +
	"\tExclusion\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\"\xb4\x01\n" +
	"\vProbeResult\x12\x19\n" +
	"\bprobe_id\x18\x01 \x01(\tR\aprobeId\x12\x15\n" +
	"\x06rtt_ms\x18\x02 \x01(\x01R\x05rttMs\x12\x1b\n" +
	"\tjitter_ms\x18\x03 \x01(\x01R\bjitterMs\x12&\n" +
	"\x0fmax_distance_km\x18\x04 \x01(\x01R\rmaxDistanceKm\x12.\n" +
	"\x13dataset_expected_ms\x18\x05 \x01(\x01R\x11datasetExpectedMs\"\xc0\x01\n" +
	"\x12SpoofingIndicators\x12\x1d\n" +
	"\n" +
	"vpn_likely\x18\x01 \x01(\bR\tvpnLikely\x12'\n" +
	"\x0fjitter_abnormal\x18\x02 \x01(\bR\x0ejitterAbnormal\x12-\n" +
	"\x12ratio_inconsistent\x18\x03 \x01(\bR\x11ratioInconsistent\x123\n" +
	"\x15physically_impossible\x18\x04 \x01(\bR\x14physicallyImpossible*x\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STATUS_CONFIRMED\x10\x01\x12\x14\n" +
	"\x10STATUS_PLAUSIBLE\x10\x02\x12\x15\n" +
	"\x11STATUS_SUSPICIOUS\x10\x03\x12\x13\n" +
	"\x0fSTATUS_REJECTED\x10\x042\xae\x01\n" +
	"\aEchoMap\x12M\n" +
	"\x0eFetchChallenge\x12\x1c.echomap.v1.ChallengeRequest\x1a\x1d.echomap.v1.ChallengeResponse\x12T\n" +
	"\x11SubmitMeasurement\x12\x1e.echomap.v1.MeasurementRequest\x1a\x1f.echomap.v1.MeasurementResponseB/Z-github.com/elninja/echomap/proto/v1;echomapv1b\x06proto3"

var (
	file_proto_v1_echomap_proto_rawDescOnce sync.Once
	file_proto_v1_echomap_proto_rawDescData []byte
)

func file_proto_v1_echomap_proto_rawDescGZIP() []byte {
	file_proto_v1_echomap_proto_rawDescOnce.Do(func() {
		file_proto_v1_echomap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_echomap_proto_rawDesc), len(file_proto_v1_echomap_proto_rawDesc)))
	})
	return file_proto_v1_echomap_proto_rawDescData
}

var file_proto_v1_echomap_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v1_echomap_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_v1_echomap_proto_goTypes = []any{
	(Status)(0),                 // 0: echomap.v1.Status
	(*ChallengeRequest)(nil),    // 1: echomap.v1.ChallengeRequest
	(*ChallengeResponse)(nil),   // 2: echomap.v1.ChallengeResponse
	(*ProbeTarget)(nil),         // 3: echomap.v1.ProbeTarget
	(*MeasurementRequest)(nil),  // 4: echomap.v1.MeasurementRequest
	(*ProbeMeasurement)(nil),    // 5: echomap.v1.ProbeMeasurement
	(*MeasurementResponse)(nil), // 6: echomap.v1.MeasurementResponse
	(*Verdict)(nil),             // 7: echomap.v1.Verdict
	(*Region)(nil),              // 8: echomap.v1.Region
	(*Exclusion)(nil),           // 9: echomap.v1.Exclusion
	(*ProbeResult)(nil),         // 10: echomap.v1.ProbeResult
	(*SpoofingIndicators)(nil),  // 11: echomap.v1.SpoofingIndicators
}
var file_proto_v1_echomap_proto_depIdxs = []int32{
	3,  // 0: echomap.v1.ChallengeResponse.targets:type_name -> echomap.v1.ProbeTarget
	5,  // 1: echomap.v1.MeasurementRequest.measurements:type_name -> echomap.v1.ProbeMeasurement
	7,  // 2: echomap.v1.MeasurementResponse.verdict:type_name -> echomap.v1.Verdict
	8,  // 3: echomap.v1.MeasurementResponse.region:type_name -> echomap.v1.Region
	9,  // 4: echomap.v1.MeasurementResponse.exclusions:type_name -> echomap.v1.Exclusion
	10, // 5: echomap.v1.MeasurementResponse.probe_results:type_name -> echomap.v1.ProbeResult
	11, // 6: echomap.v1.MeasurementResponse.spoofing:type_name -> echomap.v1.SpoofingIndicators
	0,  // 7: echomap.v1.Verdict.status:type_name -> echomap.v1.Status
	1,  // 8: echomap.v1.EchoMap.FetchChallenge:input_type -> echomap.v1.ChallengeRequest
	4,  // 9: echomap.v1.EchoMap.SubmitMeasurement:input_type -> echomap.v1.MeasurementRequest
	2,  // 10: echomap.v1.EchoMap.FetchChallenge:output_type -> echomap.v1.ChallengeResponse
	6,  // 11: echomap.v1.EchoMap.SubmitMeasurement:output_type -> echomap.v1.MeasurementResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_v1_echomap_proto_init() }
func file_proto_v1_echomap_proto_init() {
	if File_proto_v1_echomap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_echomap_proto_rawDesc), len(file_proto_v1_echomap_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_echomap_proto_goTypes,
		DependencyIndexes: file_proto_v1_echomap_proto_depIdxs,
		EnumInfos:         file_proto_v1_echomap_proto_enumTypes,
		MessageInfos:      file_proto_v1_echomap_proto_msgTypes,
	}.Build()
	File_proto_v1_echomap_proto = out.File
	file_proto_v1_echomap_proto_goTypes = nil
	file_proto_v1_echomap_proto_depIdxs = nil
}
